destination: docs
url: "https://the.independency.co"

collections:
  articles:
    output: true
    permalink: /articles/:title/
  communities:
    output: true
    permalink: /community-coalition/member/:slug/ 
  community-impact-report:
    output: true
    permalink: /community-coalition/member/:slug/impact-report
  notes:
    output: true

  


substack_feed_url: 'https://theindependencyco.substack.com/feed'


